version: '3.8'

services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ../..:/workspaces:cached
    network_mode: host      
    command: sleep infinity
    depends_on:
      - db

  db:
    image: mysql:5.7.28
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: hick
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db:/var/lib/mysql
    networks:
      - default
secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt
volumes:
  db:




